"use client";
/* eslint-disable @next/next/no-img-element -- Preview URLs are session-protected and must load with browser credentials. */
import { Download, Eye, FileText, Image as ImageIcon, Loader2, Plus, Trash2, X } from "lucide-react";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { ACTION_PLAN_LIMIT, actionPlanCategories, isPreviewable, type ActionPlan } from "@/lib/action-plan-constants";

const formatDate = (value: string) => new Intl.DateTimeFormat("es-AR", { dateStyle: "short", timeStyle: "short" }).format(new Date(value));
const formatSize = (size: number) => size < 1024 * 1024 ? `${Math.ceil(size / 1024)} KB` : `${(size / 1024 / 1024).toFixed(1)} MB`;
export function ActionPlansPanel() {
  const [documents, setDocuments] = useState<ActionPlan[]>([]); const [loading, setLoading] = useState(true); const [category, setCategory] = useState<string | null>(null); const [error, setError] = useState(""); const [preview, setPreview] = useState<ActionPlan | null>(null);
  const load = useCallback(async () => { setLoading(true); const response = await fetch("/api/action-plans"); const data = await response.json(); if (response.ok) setDocuments(data.documents); else setError(data.error || "No pudimos cargar los documentos."); setLoading(false); }, []);
  useEffect(() => { load(); }, [load]);
  const current = useMemo(() => documents.filter((item) => item.category === category), [documents, category]);
  if (category) return <main className="admin-shell"><header><p className="eyebrow">Gestión interna</p><button className="back-link" onClick={() => { setCategory(null); setError(""); }}>← Plan de acción</button><h1>{actionPlanCategories.find((item) => item.id === category)?.name}</h1><p>Documentos y medidas correctivas de esta categoría.</p></header>{error && <p className="field-error" role="alert">{error}</p>}<section className="action-plan-detail"><UploadForm category={category} full={current.length >= ACTION_PLAN_LIMIT} onCreated={(item) => { setDocuments((items) => [item, ...items]); setError(""); }} onError={setError} /><DocumentList documents={current} loading={loading} onPreview={setPreview} onDelete={async (item) => { if (!confirm(`Se eliminará definitivamente el documento “${item.title}”. Esta acción no se puede deshacer.`)) return; const response = await fetch(`/api/action-plans/${item.id}`, { method: "DELETE" }); const data = await response.json(); if (!response.ok) return setError(data.error || "No se pudo eliminar el documento."); setDocuments((items) => items.filter((entry) => entry.id !== item.id)); }} /></section>{preview && <Preview document={preview} onClose={() => setPreview(null)} />}</main>;
  return <main className="admin-shell"><header><p className="eyebrow">Gestión interna</p><h1>Plan de acción</h1><p>Documentos con acciones correctivas organizados por categoría.</p></header>{error && <p className="field-error" role="alert">{error}</p>}<section className="action-category-grid">{actionPlanCategories.map((item) => { const count = documents.filter((document) => document.category === item.id).length; return <button key={item.id} className="action-category" onClick={() => setCategory(item.id)}><FileText size={21} /><span><strong>{item.name}</strong><small>{count} / {ACTION_PLAN_LIMIT} documentos</small></span><span className={count >= ACTION_PLAN_LIMIT ? "limit-badge reached" : "limit-badge"}>{count >= ACTION_PLAN_LIMIT ? "Límite alcanzado" : "Ver documentos"}</span></button>; })}</section>{loading && <div className="loader"><Loader2 className="animate-spin" />Cargando documentos</div>}</main>;
}
function UploadForm({ category, full, onCreated, onError }: { category: string; full: boolean; onCreated: (item: ActionPlan) => void; onError: (message: string) => void }) {
  const [submitting, setSubmitting] = useState(false); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [file, setFile] = useState<File | null>(null);
  async function submit(event: FormEvent) { event.preventDefault(); onError(""); if (!title.trim()) return onError("El título es obligatorio."); if (!file) return onError("Seleccione un archivo."); setSubmitting(true); const form = new FormData(); form.set("category", category); form.set("title", title); form.set("description", description); form.set("file", file); const response = await fetch("/api/action-plans", { method: "POST", body: form }); const data = await response.json(); setSubmitting(false); if (!response.ok) return onError(data.error || "No se pudo guardar el documento."); onCreated(data.document); setTitle(""); setDescription(""); setFile(null); const input = document.getElementById("action-plan-file") as HTMLInputElement | null; if (input) input.value = ""; }
  return <form className="action-upload" onSubmit={submit}><div><p className="eyebrow">Nuevo documento</p><h2>Agregar plan</h2>{full ? <p className="limit-message">Esta categoría alcanzó los 5 documentos. Eliminá uno antes de cargar otro.</p> : <p>PDF, imágenes o documentos de Office. Máximo 20 MB.</p>}</div><label><span>Título *</span><input className="field-input" value={title} disabled={full || submitting} onChange={(event) => setTitle(event.target.value)} maxLength={180} /></label><label><span>Descripción <em>opcional</em></span><textarea className="field-input" value={description} disabled={full || submitting} onChange={(event) => setDescription(event.target.value)} maxLength={2000} rows={3} /></label><label><span>Archivo *</span><input id="action-plan-file" className="file-input" type="file" accept=".pdf,.jpg,.jpeg,.png,.webp,.doc,.docx" disabled={full || submitting} onChange={(event) => setFile(event.target.files?.[0] || null)} /></label><button className="primary-action" disabled={full || submitting}>{submitting ? <><Loader2 className="animate-spin" size={16} /> Guardando</> : <><Plus size={16} /> Guardar documento</>}</button></form>;
}
function DocumentList({ documents, loading, onPreview, onDelete }: { documents: ActionPlan[]; loading: boolean; onPreview: (item: ActionPlan) => void; onDelete: (item: ActionPlan) => void }) { if (loading) return <div className="loader"><Loader2 className="animate-spin" />Cargando documentos</div>; if (!documents.length) return <p className="empty">Todavía no hay documentos en esta categoría.</p>; return <section className="action-documents" aria-label="Documentos cargados">{documents.map((item) => <article key={item.id} className="action-document"><div className="document-icon">{item.mimeType.startsWith("image/") ? <ImageIcon size={20} /> : <FileText size={20} />}</div><div className="document-info"><h3>{item.title}</h3>{item.description && <p>{item.description}</p>}<small>{item.mimeType.split("/").pop()?.toUpperCase()} · {formatSize(item.fileSize)} · {formatDate(item.createdAt)} · Cargado por {item.uploadedBy}</small><small className="filename">{item.originalFilename}</small></div><div className="document-actions">{isPreviewable(item.mimeType) && <button title="Vista previa" aria-label={`Vista previa de ${item.title}`} onClick={() => onPreview(item)}><Eye size={18} /></button>}<a title="Descargar" aria-label={`Descargar ${item.title}`} href={`/api/action-plans/${item.id}`}><Download size={18} /></a><button title="Eliminar" aria-label={`Eliminar ${item.title}`} onClick={() => onDelete(item)}><Trash2 size={18} /></button></div></article>)}</section>; }
function Preview({ document, onClose }: { document: ActionPlan; onClose: () => void }) { const src = `/api/action-plans/${document.id}?disposition=inline`; return <div className="preview-backdrop" role="presentation" onMouseDown={onClose}><section className="preview-dialog" role="dialog" aria-modal="true" aria-label={`Vista previa de ${document.title}`} onMouseDown={(event) => event.stopPropagation()}><div><strong>{document.title}</strong><button aria-label="Cerrar vista previa" onClick={onClose}><X /></button></div>{document.mimeType === "application/pdf" ? <iframe src={src} title={document.title} /> : <img src={src} alt={document.title} />}</section></div>; }
