"use client";
import { Eye, Loader2, Search } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ratingLabel, satisfactionQuestions, surveys } from "@/lib/constants";
import type { SurveyResponse } from "@/lib/types";

export function ResponsesPanel() {
  const [responses, setResponses] = useState<SurveyResponse[]>([]), [selected, setSelected] = useState<SurveyResponse | null>(null), [loading, setLoading] = useState(true);
  const [filters, setFilters] = useState({ search:"", from:"", to:"", company:"", surveyId:"all", question:"", rating:"" });
  const load = useCallback(async () => { setLoading(true); const p = new URLSearchParams(Object.entries(filters).filter(([,v])=>v)); const data = await fetch(`/api/responses?${p}`).then(r=>r.json()); setResponses(data.responses || []); setSelected(data.responses?.[0] || null); setLoading(false); }, [filters]);
  useEffect(()=>{ load(); }, [load]);
  const companies = useMemo(()=>Array.from(new Set(responses.map(r=>r.customer.company))).sort(),[responses]);
  return <main className="admin-shell"><header><p className="eyebrow">Gestión interna</p><h1>Respuestas de clientes</h1><p>Encuestas de satisfacción · todos los módulos en un único panel.</p></header><form className="admin-filters" onSubmit={(e)=>{e.preventDefault();load();}}><input className="field-input" placeholder="Buscar cliente o responsable" value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})}/><input type="date" className="field-input" value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value})}/><input type="date" className="field-input" value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value})}/><select className="field-input" value={filters.surveyId} onChange={e=>setFilters({...filters,surveyId:e.target.value})}><option value="all">Todas las encuestas</option>{surveys.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select className="field-input" value={filters.company} onChange={e=>setFilters({...filters,company:e.target.value})}><option value="">Todos los clientes</option>{companies.map(c=><option key={c}>{c}</option>)}</select><select className="field-input" value={filters.question} onChange={e=>setFilters({...filters,question:e.target.value,rating:""})}><option value="">Todas las preguntas</option>{satisfactionQuestions.map(q=><option key={q.key} value={q.key}>{q.order}. {q.label}</option>)}</select><select className="field-input" value={filters.rating} disabled={!filters.question} onChange={e=>setFilters({...filters,rating:e.target.value})}><option value="">Toda valoración</option><option value="1">Malo</option><option value="2">Regular</option><option value="3">Bueno</option><option value="4">Muy bueno</option><option value="5">Excelente</option><option value="null">No contestar</option></select><button className="primary-action"><Search size={17}/>Aplicar</button></form><div className="response-layout"><section className="response-list">{loading?<div className="loader"><Loader2 className="animate-spin"/>Cargando respuestas</div>:responses.length?responses.map(r=><button key={r.id} className={selected?.id===r.id?"response-row active":"response-row"} onClick={()=>setSelected(r)}><span>{date(r.createdAt)}</span><strong>{r.customer.company}</strong><small>{r.customer.contactName}</small><Eye size={17}/></button>):<p className="empty">No hay respuestas para los filtros elegidos.</p>}</section><Detail response={selected}/></div></main>;
}
function Detail({response}:{response:SurveyResponse|null}) { if(!response)return <aside className="detail-panel empty">Seleccione una respuesta.</aside>; return <aside className="detail-panel"><p className="eyebrow">Encuesta individual</p><h2>{response.customer.company}</h2><p className="detail-meta">{response.customer.contactName}{response.customer.position?` · ${response.customer.position}`:""}</p><p className="detail-meta">{date(response.createdAt)} · {response.satisfaction.module}</p><div className="answer-list">{satisfactionQuestions.map(q=><div key={q.key}><span>{q.order}. {q.label}</span><strong>{ratingLabel(response.satisfaction.ratings[q.key])}</strong></div>)}</div>{response.satisfaction.additionalComments&&<section className="comment-detail"><p>Comentario</p><span>{response.satisfaction.additionalComments}</span></section>}</aside>; }
const date=(value:string)=>new Intl.DateTimeFormat("es-AR",{dateStyle:"short",timeStyle:"short"}).format(new Date(value));
